/**
 * Regenerates platform deploy files from deploy/config.ts.
 * Run: pnpm deploy:sync
 */
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { deployConfig } from "./config"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const GENERATED =
    "Generated by `pnpm deploy:sync`. Edit `deploy/config.ts`, then re-run sync."

function write(relPath: string, contents: string) {
    const abs = join(root, relPath)
    mkdirSync(dirname(abs), { recursive: true })
    writeFileSync(abs, contents.endsWith("\n") ? contents : `${contents}\n`)
    console.log(`wrote ${relPath}`)
}

function dockerfile(): string {
    const { port, buildCommand, containerStartCommand } = deployConfig
    return `# ${GENERATED}
# syntax=docker/dockerfile:1

FROM node:22-alpine AS base
RUN corepack enable && corepack prepare pnpm@10.12.1 --activate
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-lock.yaml ./
COPY patches ./patches
RUN pnpm install --frozen-lockfile

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN ${buildCommand}

FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=${port}
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \\
	&& adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/patches ./patches
COPY --from=builder /app/next.config.ts ./next.config.ts
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/migrations ./migrations
COPY --from=builder /app/drizzle.config.ts ./drizzle.config.ts
COPY --from=builder /app/src/database ./src/database

USER nextjs
EXPOSE ${port}

# Migrate at container start (needs DATABASE_URL), then start Next.js
CMD ["sh", "-c", "${containerStartCommand}"]
`
}

function dockerignore(): string {
    return `# ${GENERATED}
node_modules
.next
.git
.env
.env.*
!.env.example
*.md
.cursor
.turbo
coverage
agent-transcripts
`
}

function dockerCompose(): string {
    const { name, port, dokploy } = deployConfig
    const router = dokploy.routerName
    const domain = dokploy.domain
    return `# ${GENERATED}
# Dokploy: Compose path ./docker-compose.yml — set dokploy.domain in deploy/config.ts then re-sync.

services:
  ${name}:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${port}"
    environment:
      - DATABASE_URL=\${DATABASE_URL}
      - BETTER_AUTH_SECRET=\${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=\${BETTER_AUTH_URL}
      - PORT=${port}
      - HOSTNAME=0.0.0.0
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${router}.rule=Host(\`${domain}\`)"
      - "traefik.http.routers.${router}.entrypoints=websecure"
      - "traefik.http.routers.${router}.tls.certResolver=letsencrypt"
      - "traefik.http.services.${router}.loadbalancer.server.port=${port}"

networks:
  dokploy-network:
    external: true
`
}

function railwayToml(): string {
    const { healthcheckPath } = deployConfig
    return `# ${GENERATED}

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "${healthcheckPath}"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
`
}

function wranglerContainers(): string {
    const { name, cloudflare } = deployConfig
    const className = cloudflare.containerClassName
    return `// ${GENERATED}
// Cloudflare runtime: containers (default)
{
	"$schema": "./node_modules/wrangler/config-schema.json",
	"name": "${name}",
	"main": "${cloudflare.containerWorker}",
	"compatibility_date": "2026-07-01",
	"compatibility_flags": ["nodejs_compat"],
	"containers": [
		{
			"class_name": "${className}",
			"image": "./Dockerfile",
			"max_instances": 3
		}
	],
	"durable_objects": {
		"bindings": [
			{
				"class_name": "${className}",
				"name": "AUTH_SERVER"
			}
		]
	},
	"migrations": [
		{
			"tag": "v1",
			"new_sqlite_classes": ["${className}"]
		}
	],
	"observability": {
		"enabled": true
	}
}
`
}

function wranglerWorkers(): string {
    const { name } = deployConfig
    return `// ${GENERATED}
// Cloudflare runtime: workers (OpenNext)
// Install: pnpm add -D wrangler @opennextjs/cloudflare
// Postgres: configure Hyperdrive and bind it in this file (see docs/framework/deployment.mdx).
{
	"$schema": "./node_modules/wrangler/config-schema.json",
	"name": "${name}",
	"main": ".open-next/worker.js",
	"compatibility_date": "2026-07-01",
	"compatibility_flags": ["nodejs_compat"],
	"assets": {
		"directory": ".open-next/assets",
		"binding": "ASSETS"
	},
	"observability": {
		"enabled": true
	}
}
`
}

function openNextConfig(): string {
    return `// ${GENERATED}
// Used when deployConfig.cloudflare.runtime === "workers".
import { defineCloudflareConfig } from "@opennextjs/cloudflare"

export default defineCloudflareConfig()
`
}

function main() {
    write("Dockerfile", dockerfile())
    write(".dockerignore", dockerignore())
    write("docker-compose.yml", dockerCompose())
    write("railway.toml", railwayToml())

    if (deployConfig.cloudflare.runtime === "workers") {
        write("wrangler.jsonc", wranglerWorkers())
        write("open-next.config.ts", openNextConfig())
    } else {
        write("wrangler.jsonc", wranglerContainers())
    }

    console.log(
        `\ndeploy sync complete (cloudflare.runtime=${deployConfig.cloudflare.runtime})`
    )
}

main()
